- src: git+https://github.com/wikitops/ansible_docker
  version: "1.5"
  name: docker

- src: git+https://github.com/wikitops/ansible_epel
  version: "1.2"
  name: epel

- src: git+https://github.com/wikitops/ansible_halyard
  version: "1.1"
  name: halyard

- src: git+https://github.com/wikitops/ansible_minio
  version: "1.0"
  name: minio

- src: git+https://github.com/wikitops/ansible_pip
  version: "1.2"
  name: pip
