---

- name: MINIO ON DOCKER | Install prerequisites
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - python-pip

- name: MINIO ON DOCKER | Install dependencies
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - docker

- name: MINIO ON DOCKER | Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /data/minio/data
    - /data/minio/config

- name: MINIO ON DOCKER | Run the container
  docker_container:
    state: started
    name: minio1
    image: minio/minio
    recreate: yes
    tty: yes
    exposed_ports:
      - 9090:9000
    volumes:
      - "/data/minio/data:/data"
      - "/data/minio/config:/root/.minio"
    command: server /data
    env:
      MINIO_ACCESS_KEY: "{{ minio_access_key }}"
      MINIO_SECRET_KEY: "{{ minio_secret_key }}"
